version: "3"

services:
  php:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/backend
    networks:
      - xeno_portal
    links:
      - database
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/backend/public
    ports:
      - "8081:8081"
    depends_on:
      - php
    networks:
      - xeno_portal
    links:
      - database

  # The Database
  database:
    build:
      context: ./docker/database
      dockerfile: dockerfile
    container_name: database
    volumes:
      - ./docker/database/db:/Applications/MAMP/Library/bin/mysql
    ports:
      - 8991:3306
    networks:
      - xeno_portal
  # worker:
  #   container_name: xeno-portal-worker
  #   build:
  #     context: .
  #     dockerfile: ./docker/worker/Dockerfile
  #   volumes:
  #     - ./:/var/www/backend
  #   depends_on:
  #     - php
  #   networks:
    #   - xeno_portal
networks:
  xeno_portal:
    name: xeno_portal
    driver: bridge

