version: '3'
services:
  admin:
    container_name: admin
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    image: xeno-admin
    environment:
      - ENV_NAME=${ENV_NAME}
      - API_HOST=${API_HOST}
    ports:
      - '80:80'
